### ISSUE TITLE
Something went wrong!

### ISSUE THREAD

**Issue by SeaSharkDEV** [Akascape/Sprite-Extracter-On-The-Go#3]
When I input image sheet and image data and trying to extract, it fails with Something Went Wrong error
![Screenshot_2](https://github.com/Akascape/Sprite-Extractor-On-The-Go/assets/97847034/60b80e7b-c341-4a1c-b802-c2080264f5fe)

**Comment by punctdan** [comment]
I have the same issue by using .png and .xml files.

**Comment by Akascape** [comment]
can you give me the xml and png file to test the thing?

**Comment by punctdan** [comment]
> can you give me the xml and png file to test the thing?

Here's the link to the files:
https://drive.google.com/drive/folders/17PjOp1QzEbUz14SIc9yy9T5Eznb_T6IB?usp=drive_link

**Comment by SeaSharkDEV** [comment]
So any ideas why that's happening?

**Comment by H357753** [comment]
yes,I have the same problem.
You can use the [Releases](https://github.com/Akascape/Sprite-Extractor-On-The-Go/releases/tag/Sprite_Extracter_On-The-Go.zip).

**Comment by Akascape** [comment]
@punctdan @H357753 @SeaSharkDEV Try the latest version.

**Comment by H357753** [comment]
I will.
Thank  you.

**Comment by H357753** [comment]
@Akascape hi, bro. The problem is still not solved

**Comment by H357753** [comment]
something was wrong

**Comment by Akascape** [comment]
@H357753 Send me the xml file. It's because many xml files have different attribute names.

**Comment by Akascape** [comment]
@H357753 Try these xml files.

https://drive.google.com/drive/folders/17PjOp1QzEbUz14SIc9yy9T5Eznb_T6IB?usp=drive_link

I fixed the error on this basis

**Comment by H357753** [comment]
This file has the correct picture in it

**Comment by punctdan** [comment]
@Akascape The latest version works flawlessly. Thanks for patching it up!

**Comment by Akascape** [comment]
@H357753 Fixed, it was a issue with the name attribute.

**Comment by H357753** [comment]
oh, thank you bro.
